// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['api']['App']['Close']();
}

export function CreateNoteHTML(arg1, arg2) {
  return window['go']['api']['App']['CreateNoteHTML'](arg1, arg2);
}

export function CreateTemplateHTML(arg1, arg2) {
  return window['go']['api']['App']['CreateTemplateHTML'](arg1, arg2);
}

export function EditAssets(arg1, arg2) {
  return window['go']['api']['App']['EditAssets'](arg1, arg2);
}

export function EditData(arg1) {
  return window['go']['api']['App']['EditData'](arg1);
}

export function EditNote(arg1, arg2) {
  return window['go']['api']['App']['EditNote'](arg1, arg2);
}

export function GetData(arg1, arg2) {
  return window['go']['api']['App']['GetData'](arg1, arg2);
}

export function GetNote(arg1) {
  return window['go']['api']['App']['GetNote'](arg1);
}

export function GetResource() {
  return window['go']['api']['App']['GetResource']();
}

export function OpenData(arg1, arg2) {
  return window['go']['api']['App']['OpenData'](arg1, arg2);
}

export function OpenNote(arg1) {
  return window['go']['api']['App']['OpenNote'](arg1);
}

export function OpenTemplate(arg1) {
  return window['go']['api']['App']['OpenTemplate'](arg1);
}

export function SaveData(arg1, arg2, arg3) {
  return window['go']['api']['App']['SaveData'](arg1, arg2, arg3);
}

export function SaveNote(arg1, arg2) {
  return window['go']['api']['App']['SaveNote'](arg1, arg2);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['api']['App']['SaveTemplate'](arg1, arg2);
}

export function SelectFile(arg1, arg2) {
  return window['go']['api']['App']['SelectFile'](arg1, arg2);
}

export function SetCurrent(arg1) {
  return window['go']['api']['App']['SetCurrent'](arg1);
}
