// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemote(arg1, arg2) {
  return window['go']['api']['App']['AddRemote'](arg1, arg2);
}

export function Address() {
  return window['go']['api']['App']['Address']();
}

export function CloseBinder() {
  return window['go']['api']['App']['CloseBinder']();
}

export function Commit(arg1, arg2, arg3) {
  return window['go']['api']['App']['Commit'](arg1, arg2, arg3);
}

export function CreateBinder(arg1, arg2, arg3) {
  return window['go']['api']['App']['CreateBinder'](arg1, arg2, arg3);
}

export function CreateNoteHTML(arg1, arg2) {
  return window['go']['api']['App']['CreateNoteHTML'](arg1, arg2);
}

export function CreateRemoteBinder(arg1, arg2) {
  return window['go']['api']['App']['CreateRemoteBinder'](arg1, arg2);
}

export function CreateTemplateHTML(arg1, arg2, arg3) {
  return window['go']['api']['App']['CreateTemplateHTML'](arg1, arg2, arg3);
}

export function EditAsset(arg1, arg2) {
  return window['go']['api']['App']['EditAsset'](arg1, arg2);
}

export function EditConfig(arg1) {
  return window['go']['api']['App']['EditConfig'](arg1);
}

export function EditDiagram(arg1) {
  return window['go']['api']['App']['EditDiagram'](arg1);
}

export function EditNote(arg1, arg2) {
  return window['go']['api']['App']['EditNote'](arg1, arg2);
}

export function EditTemplate(arg1) {
  return window['go']['api']['App']['EditTemplate'](arg1);
}

export function Generate(arg1, arg2, arg3) {
  return window['go']['api']['App']['Generate'](arg1, arg2, arg3);
}

export function GetAsset(arg1) {
  return window['go']['api']['App']['GetAsset'](arg1);
}

export function GetBinderTree() {
  return window['go']['api']['App']['GetBinderTree']();
}

export function GetConfig() {
  return window['go']['api']['App']['GetConfig']();
}

export function GetDiagram(arg1) {
  return window['go']['api']['App']['GetDiagram'](arg1);
}

export function GetHTMLTemplates() {
  return window['go']['api']['App']['GetHTMLTemplates']();
}

export function GetNote(arg1) {
  return window['go']['api']['App']['GetNote'](arg1);
}

export function GetSetting() {
  return window['go']['api']['App']['GetSetting']();
}

export function GetTemplate(arg1) {
  return window['go']['api']['App']['GetTemplate'](arg1);
}

export function GetTemplateTree() {
  return window['go']['api']['App']['GetTemplateTree']();
}

export function LoadBinder(arg1) {
  return window['go']['api']['App']['LoadBinder'](arg1);
}

export function OpenBinderSite() {
  return window['go']['api']['App']['OpenBinderSite']();
}

export function OpenDiagram(arg1) {
  return window['go']['api']['App']['OpenDiagram'](arg1);
}

export function OpenNote(arg1) {
  return window['go']['api']['App']['OpenNote'](arg1);
}

export function OpenTemplate(arg1) {
  return window['go']['api']['App']['OpenTemplate'](arg1);
}

export function ParseNote(arg1, arg2, arg3) {
  return window['go']['api']['App']['ParseNote'](arg1, arg2, arg3);
}

export function Remotes() {
  return window['go']['api']['App']['Remotes']();
}

export function RemoveDiagram(arg1) {
  return window['go']['api']['App']['RemoveDiagram'](arg1);
}

export function RemoveNote(arg1) {
  return window['go']['api']['App']['RemoveNote'](arg1);
}

export function SaveDiagram(arg1, arg2) {
  return window['go']['api']['App']['SaveDiagram'](arg1, arg2);
}

export function SaveNote(arg1, arg2) {
  return window['go']['api']['App']['SaveNote'](arg1, arg2);
}

export function SaveSetting(arg1) {
  return window['go']['api']['App']['SaveSetting'](arg1);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['api']['App']['SaveTemplate'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['api']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['api']['App']['SelectFile'](arg1, arg2);
}

export function SetCurrent(arg1) {
  return window['go']['api']['App']['SetCurrent'](arg1);
}

export function Terminate() {
  return window['go']['api']['App']['Terminate']();
}
