// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {binder} from '../models';
import {fs} from '../models';

export function Address():Promise<string>;

export function Close():Promise<boolean>;

export function CreateNoteHTML(arg1:string,arg2:string):Promise<string>;

export function CreateTemplateHTML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EditAssets(arg1:model.Datum,arg2:string):Promise<model.Datum>;

export function EditData(arg1:model.Datum):Promise<model.Datum>;

export function EditNote(arg1:model.Note,arg2:string):Promise<model.Note>;

export function GetData(arg1:string,arg2:string):Promise<model.Datum>;

export function GetNote(arg1:string):Promise<model.Note>;

export function GetResource():Promise<binder.Resource>;

export function OpenData(arg1:string,arg2:string):Promise<string>;

export function OpenNote(arg1:string):Promise<string>;

export function OpenTemplate(arg1:string):Promise<string>;

export function SaveData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<void>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetCurrent(arg1:fs.Binder):Promise<void>;
