// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';
import {binder} from '../models';
import {settings} from '../models';

export function AddRemote(arg1:string,arg2:string):Promise<void>;

export function Address():Promise<string>;

export function CloseBinder():Promise<void>;

export function Commit(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CommitFiles(arg1:Array<json.Leaf>,arg2:string):Promise<void>;

export function CreateBinder(arg1:string,arg2:string):Promise<string>;

export function CreateNoteHTML(arg1:string,arg2:string):Promise<string>;

export function CreateRemoteBinder(arg1:string,arg2:string):Promise<string>;

export function CreateTemplateHTML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EditAsset(arg1:json.Asset,arg2:string):Promise<json.Asset>;

export function EditConfig(arg1:json.Config):Promise<json.Config>;

export function EditDiagram(arg1:json.Diagram):Promise<json.Diagram>;

export function EditNote(arg1:json.Note,arg2:string):Promise<json.Note>;

export function EditTemplate(arg1:json.Template):Promise<json.Template>;

export function Generate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAsset(arg1:string):Promise<json.Asset>;

export function GetBinderTree():Promise<json.Tree>;

export function GetConfig():Promise<json.Config>;

export function GetDiagram(arg1:string):Promise<json.Diagram>;

export function GetFontNames():Promise<Array<string>>;

export function GetHTMLTemplates():Promise<json.Templates>;

export function GetModifiedTree():Promise<json.Tree>;

export function GetNote(arg1:string):Promise<json.Note>;

export function GetNowPatch(arg1:string,arg2:string):Promise<binder.Patch>;

export function GetSetting():Promise<settings.Setting>;

export function GetTemplate(arg1:string):Promise<json.Template>;

export function GetTemplateTree():Promise<json.Tree>;

export function GetUnpublishedTree():Promise<json.Tree>;

export function LoadBinder(arg1:string):Promise<string>;

export function OpenBinderSite():Promise<void>;

export function OpenDiagram(arg1:string):Promise<string>;

export function OpenNote(arg1:string):Promise<string>;

export function OpenTemplate(arg1:string):Promise<string>;

export function ParseNote(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function Remotes():Promise<Array<string>>;

export function RemoveAsset(arg1:string):Promise<void>;

export function RemoveDiagram(arg1:string):Promise<void>;

export function RemoveNote(arg1:string):Promise<void>;

export function RunEditor(arg1:string,arg2:string):Promise<void>;

export function SaveDiagram(arg1:string,arg2:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function SavePosition():Promise<void>;

export function SaveSetting(arg1:settings.Setting):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory(arg1:boolean):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetCurrent(arg1:binder.Binder):Promise<void>;

export function Terminate():Promise<boolean>;
