// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {binder} from '../models';
import {api} from '../models';
import {settings} from '../models';

export function AddRemote(arg1:string,arg2:string):Promise<void>;

export function Address():Promise<string>;

export function CloseBinder():Promise<void>;

export function Commit(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateBinder(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateNoteHTML(arg1:string,arg2:string):Promise<string>;

export function CreateRemoteBinder(arg1:string,arg2:string):Promise<void>;

export function CreateTemplateHTML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EditAsset(arg1:model.Asset,arg2:string):Promise<model.Asset>;

export function EditConfig(arg1:model.Config):Promise<model.Config>;

export function EditDiagram(arg1:model.Diagram):Promise<model.Diagram>;

export function EditNote(arg1:model.Note,arg2:string):Promise<model.Note>;

export function EditTemplate(arg1:model.Template):Promise<model.Template>;

export function Generate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAsset(arg1:string):Promise<model.Asset>;

export function GetBinderTree():Promise<binder.Tree>;

export function GetConfig():Promise<model.Config>;

export function GetDiagram(arg1:string):Promise<model.Diagram>;

export function GetHTMLTemplates():Promise<api.Templates>;

export function GetNote(arg1:string):Promise<model.Note>;

export function GetSetting():Promise<settings.Setting>;

export function GetTemplate(arg1:string):Promise<model.Template>;

export function GetTemplateTree():Promise<binder.Tree>;

export function LoadBinder(arg1:string):Promise<void>;

export function OpenBinderSite():Promise<void>;

export function OpenDiagram(arg1:string):Promise<string>;

export function OpenNote(arg1:string):Promise<string>;

export function OpenTemplate(arg1:string):Promise<string>;

export function ParseNote(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function Remotes():Promise<Array<string>>;

export function RemoveAsset(arg1:string):Promise<void>;

export function RemoveDiagram(arg1:string):Promise<void>;

export function RemoveNote(arg1:string):Promise<void>;

export function SaveDiagram(arg1:string,arg2:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function SavePosition():Promise<void>;

export function SaveSetting(arg1:settings.Setting):Promise<void>;

export function SaveTemplate(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory(arg1:boolean):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetCurrent(arg1:binder.Binder):Promise<void>;

export function Terminate():Promise<boolean>;
