// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as binder$0 from "../models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "./json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function AddRemote(name, url) {
    return $Call.ByID(1386052904, name, url);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Address() {
    return $Call.ByID(1530103829);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseBinder() {
    return $Call.ByID(1548944049);
}

/**
 * @param {string} mode
 * @param {string} id
 * @param {string} m
 * @returns {$CancellablePromise<void>}
 */
export function Commit(mode, id, m) {
    return $Call.ByID(434280990, mode, id, m);
}

/**
 * @param {(json$0.Leaf | null)[]} leafs
 * @param {string} m
 * @returns {$CancellablePromise<void>}
 */
export function CommitFiles(leafs, m) {
    return $Call.ByID(2495371281, leafs, m);
}

/**
 * @param {string} dir
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CreateBinder(dir, name) {
    return $Call.ByID(3177247199, dir, name);
}

/**
 * @param {string} id
 * @param {string} elm
 * @returns {$CancellablePromise<string>}
 */
export function CreateNoteHTML(id, elm) {
    return $Call.ByID(2614281698, id, elm);
}

/**
 * @param {string} url
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function CreateRemoteBinder(url, dir) {
    return $Call.ByID(626691569, url, dir);
}

/**
 * @param {string} id
 * @param {string} data
 * @param {string} elm
 * @returns {$CancellablePromise<string>}
 */
export function CreateTemplateHTML(id, data, elm) {
    return $Call.ByID(3655212360, id, data, elm);
}

/**
 * @param {json$0.Asset | null} $as
 * @param {string} filename
 * @param {string} base64data
 * @returns {$CancellablePromise<json$0.Asset | null>}
 */
export function DropAsset($as, filename, base64data) {
    return $Call.ByID(515404762, $as, filename, base64data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {json$0.Asset | null} $as
 * @param {string} file
 * @returns {$CancellablePromise<json$0.Asset | null>}
 */
export function EditAsset($as, file) {
    return $Call.ByID(3541038605, $as, file).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {json$0.Config | null} conf
 * @returns {$CancellablePromise<json$0.Config | null>}
 */
export function EditConfig(conf) {
    return $Call.ByID(740331705, conf).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {json$0.Diagram | null} d
 * @returns {$CancellablePromise<json$0.Diagram | null>}
 */
export function EditDiagram(d) {
    return $Call.ByID(1571423304, d).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {json$0.Note | null} n
 * @param {string} imageName
 * @returns {$CancellablePromise<json$0.Note | null>}
 */
export function EditNote(n, imageName) {
    return $Call.ByID(2758456587, n, imageName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {json$0.Template | null} t
 * @returns {$CancellablePromise<json$0.Template | null>}
 */
export function EditTemplate(t) {
    return $Call.ByID(3545763161, t).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} mode
 * @param {string} id
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Generate(mode, id, data) {
    return $Call.ByID(258221536, mode, id, data);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<json$0.Asset | null>}
 */
export function GetAsset(id) {
    return $Call.ByID(1604931919, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAssetContent はアセットファイルの内容を base64 エンコードして返す。
 * AssetContent.Binary が true の場合はバイナリ、false の場合はテキストファイル。
 * @param {string} id
 * @returns {$CancellablePromise<json$0.AssetContent | null>}
 */
export function GetAssetContent(id) {
    return $Call.ByID(2381067512, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.Tree | null>}
 */
export function GetBinderTree() {
    return $Call.ByID(2685130125).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(3701565011).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<json$0.Diagram | null>}
 */
export function GetDiagram(id) {
    return $Call.ByID(1636256050, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFontNames() {
    return $Call.ByID(3495059948).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.Templates | null>}
 */
export function GetHTMLTemplates() {
    return $Call.ByID(3234023383).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.Tree | null>}
 */
export function GetModifiedTree() {
    return $Call.ByID(463238562).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<json$0.Note | null>}
 */
export function GetNote(id) {
    return $Call.ByID(1151140297, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} typ
 * @param {string} id
 * @returns {$CancellablePromise<binder$0.Patch | null>}
 */
export function GetNowPatch(typ, id) {
    return $Call.ByID(3682172215, typ, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<settings$0.Setting | null>}
 */
export function GetSetting() {
    return $Call.ByID(63257543).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<json$0.Template | null>}
 */
export function GetTemplate(id) {
    return $Call.ByID(3825183639, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.Tree | null>}
 */
export function GetTemplateTree() {
    return $Call.ByID(207242683).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<json$0.Tree | null>}
 */
export function GetUnpublishedTree() {
    return $Call.ByID(655040332).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * ImportLocalFiles は OS のファイルパス一覧を受け取り、各ファイルを指定ノートのアセットとして登録する。
 * Wails ネイティブファイルドロップ (EnableFileDrop) から Go ハンドラ経由で呼び出される。
 * @param {string} parentId
 * @param {string[]} filePaths
 * @returns {$CancellablePromise<void>}
 */
export function ImportLocalFiles(parentId, filePaths) {
    return $Call.ByID(1451623208, parentId, filePaths);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<string>}
 */
export function LoadBinder(dir) {
    return $Call.ByID(3086360527, dir);
}

/**
 * @param {string} parentId
 * @param {string[]} childIds
 * @returns {$CancellablePromise<void>}
 */
export function MoveNode(parentId, childIds) {
    return $Call.ByID(3004732458, parentId, childIds);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenBinderSite() {
    return $Call.ByID(1956034536);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function OpenDiagram(id) {
    return $Call.ByID(2938807272, id);
}

/**
 * @param {string} noteId
 * @returns {$CancellablePromise<string>}
 */
export function OpenNote(noteId) {
    return $Call.ByID(2652285227, noteId);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function OpenTemplate(id) {
    return $Call.ByID(1627300473, id);
}

/**
 * @param {string} id
 * @param {boolean} local
 * @param {string} elm
 * @returns {$CancellablePromise<string>}
 */
export function ParseNote(id, local, elm) {
    return $Call.ByID(105338406, id, local, elm);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function Remotes() {
    return $Call.ByID(1373910066).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAsset(id) {
    return $Call.ByID(1246349293, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveDiagram(id) {
    return $Call.ByID(1946457128, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveNote(id) {
    return $Call.ByID(1574566763, id);
}

/**
 * @param {string} mode
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RunEditor(mode, id) {
    return $Call.ByID(3486810297, mode, id);
}

/**
 * @param {string} id
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveDiagram(id, data) {
    return $Call.ByID(139823187, id, data);
}

/**
 * @param {string} noteId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveNote(noteId, data) {
    return $Call.ByID(262308670, noteId, data);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SavePosition() {
    return $Call.ByID(1737332589);
}

/**
 * @param {settings$0.Setting | null} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetting(s) {
    return $Call.ByID(4274553598, s);
}

/**
 * @param {string} id
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function SaveTemplate(id, data) {
    return $Call.ByID(1558150868, id, data);
}

/**
 * @param {boolean} create
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(create) {
    return $Call.ByID(1225829662, create);
}

/**
 * @param {string} name
 * @param {string} ptn
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile(name, ptn) {
    return $Call.ByID(158382265, name, ptn);
}

/**
 * @param {binder$0.Binder | null} c
 * @returns {$CancellablePromise<void>}
 */
export function SetCurrent(c) {
    return $Call.ByID(1900983858, c);
}

/**
 * SetRuntime は AppRuntime の実装を注入する。
 * Wails v3 を使う場合は _cmd/binder/main.go 内で呼び出す。
 * @param {$models.AppRuntime} r
 * @returns {$CancellablePromise<void>}
 */
export function SetRuntime(r) {
    return $Call.ByID(1076124227, r);
}

/**
 * Startup は起動時の初期化処理を行う。
 * Wails v3 の ServiceStartup とは切り離されており、main() から直接呼び出せる。
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(1457916904);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function Terminate() {
    return $Call.ByID(4145435618);
}

// Private type creation functions
const $$createType0 = json$0.Asset.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = json$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = json$0.Diagram.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = json$0.Note.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = json$0.Template.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = json$0.AssetContent.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = json$0.Tree.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = json$0.Templates.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = binder$0.Patch.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = settings$0.Setting.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
