// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppRuntime はデスクトップ環境の操作を抽象化するインターフェース。
 * 具体的な実装（Wails v3 等）は _cmd/binder 層で提供し、
 * binder パッケージ自体が Wails v3 に依存しない設計とする。
 * @typedef {any} AppRuntime
 */
