// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class Asset {
    /**
     * Creates a new Asset instance.
     * @param {Partial<Asset>} [$$source = {}] - The source object to create the Asset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("binary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binary"] = false;
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (!("createdUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdUser"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated"] = null;
        }
        if (!("updatedUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedUser"] = "";
        }
        if (!("publishStatus" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["publishStatus"] = Status.$zero;
        }
        if (!("updatedStatus" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["updatedStatus"] = Status.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Asset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Asset(/** @type {Partial<Asset>} */($$parsedSource));
    }
}

/**
 * AssetContent はアセットのメタデータとファイル内容を合わせた型。
 * GetAssetContent() API で返却される。Content は常に base64 エンコードされた文字列。
 */
export class AssetContent {
    /**
     * Creates a new AssetContent instance.
     * @param {Partial<AssetContent>} [$$source = {}] - The source object to create the AssetContent.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("binary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["binary"] = false;
        }
        if (!("content" in $$source)) {
            /**
             * base64 encoded
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetContent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetContent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetContent(/** @type {Partial<AssetContent>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote"] = "";
        }
        if (!("markedUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["markedUrl"] = "";
        }
        if (!("mermaidUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mermaidUrl"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (!("createdUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdUser"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated"] = null;
        }
        if (!("updatedUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedUser"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class Diagram {
    /**
     * Creates a new Diagram instance.
     * @param {Partial<Diagram>} [$$source = {}] - The source object to create the Diagram.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("publish" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["publish"] = null;
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (!("createdUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdUser"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated"] = null;
        }
        if (!("updatedUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedUser"] = "";
        }
        if (!("publishStatus" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["publishStatus"] = Status.$zero;
        }
        if (!("updatedStatus" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["updatedStatus"] = Status.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagram instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diagram}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagram(/** @type {Partial<Diagram>} */($$parsedSource));
    }
}

export class Leaf {
    /**
     * Creates a new Leaf instance.
     * @param {Partial<Leaf>} [$$source = {}] - The source object to create the Leaf.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {(Leaf | null)[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Leaf instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Leaf}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new Leaf(/** @type {Partial<Leaf>} */($$parsedSource));
    }
}

export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("layoutTemplate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["layoutTemplate"] = "";
        }
        if (!("contentTemplate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contentTemplate"] = "";
        }
        if (!("publish" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["publish"] = null;
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (!("createdUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdUser"] = "";
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated"] = null;
        }
        if (!("updatedUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedUser"] = "";
        }
        if (!("publishStatus" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["publishStatus"] = Status.$zero;
        }
        if (!("updatedStatus" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["updatedStatus"] = Status.$zero;
        }
        if (!("layouts" in $$source)) {
            /**
             * @member
             * @type {(Template | null)[]}
             */
            this["layouts"] = [];
        }
        if (!("contents" in $$source)) {
            /**
             * @member
             * @type {(Template | null)[]}
             */
            this["contents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType5;
        const $$createField15_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layouts" in $$parsedSource) {
            $$parsedSource["layouts"] = $$createField14_0($$parsedSource["layouts"]);
        }
        if ("contents" in $$parsedSource) {
            $$parsedSource["contents"] = $$createField15_0($$parsedSource["contents"]);
        }
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    ErrorStatus: -1,
    LatestStatus: 0,
    PrivateStatus: 1,
    UpdatedStatus: 2,
    NothingStatus: 0,
    ModifiedStatus: 1,
};

export class Template {
    /**
     * Creates a new Template instance.
     * @param {Partial<Template>} [$$source = {}] - The source object to create the Template.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created"] = null;
        }
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated"] = null;
        }
        if (!("updatedStatus" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["updatedStatus"] = Status.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Template instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Template}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Template(/** @type {Partial<Template>} */($$parsedSource));
    }
}

export class Templates {
    /**
     * Creates a new Templates instance.
     * @param {Partial<Templates>} [$$source = {}] - The source object to create the Templates.
     */
    constructor($$source = {}) {
        if (!("layouts" in $$source)) {
            /**
             * @member
             * @type {(Template | null)[]}
             */
            this["layouts"] = [];
        }
        if (!("contents" in $$source)) {
            /**
             * @member
             * @type {(Template | null)[]}
             */
            this["contents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Templates instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Templates}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layouts" in $$parsedSource) {
            $$parsedSource["layouts"] = $$createField0_0($$parsedSource["layouts"]);
        }
        if ("contents" in $$parsedSource) {
            $$parsedSource["contents"] = $$createField1_0($$parsedSource["contents"]);
        }
        return new Templates(/** @type {Partial<Templates>} */($$parsedSource));
    }
}

export class Tree {
    /**
     * Creates a new Tree instance.
     * @param {Partial<Tree>} [$$source = {}] - The source object to create the Tree.
     */
    constructor($$source = {}) {
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {(Leaf | null)[]}
             */
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tree instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tree}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        return new Tree(/** @type {Partial<Tree>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Leaf.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Template.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
