// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateData(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateData'](arg1, arg2, arg3);
}

export function CreateHTML(arg1, arg2) {
  return window['go']['main']['App']['CreateHTML'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function GetResource() {
  return window['go']['main']['App']['GetResource']();
}

export function OpenData(arg1, arg2) {
  return window['go']['main']['App']['OpenData'](arg1, arg2);
}

export function OpenNote(arg1) {
  return window['go']['main']['App']['OpenNote'](arg1);
}

export function SaveData(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveData'](arg1, arg2, arg3);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}
