// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {binder} from '../models';

export function Close():Promise<boolean>;

export function CreateData(arg1:string,arg2:string,arg3:string):Promise<model.Datum>;

export function CreateHTML(arg1:string,arg2:string):Promise<string>;

export function CreateNote(arg1:string,arg2:string,arg3:string):Promise<model.Note>;

export function GetResource():Promise<binder.Resource>;

export function OpenData(arg1:string,arg2:string):Promise<string>;

export function OpenNote(arg1:string):Promise<string>;

export function SaveData(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;
