// Code generated by model/asset.go; DO NOT EDIT.
// 2024-09-10 05:22:40.3388596 +0900 JST m=+0.016013501
package db

import (
    "database/sql"
    "errors"
    "fmt"
    "path/filepath"
    "strings"
    "time"

    "binder/db/model"

	"golang.org/x/xerrors"
)

// create table
func createAssetTable(dir string) error {
    return createTableFile(filepath.Join(dir,"assets.csv"),"id,parent_id,name,detail,created_date,created_user,updated_date,updated_user")
}

// exists check key
func (inst *Instance) existAsset(id string) bool {
    m,err := inst.GetAsset(id)
    if err != nil || m == nil {
        return false
    }
    return true
}

// get row 
func (inst *Instance) GetAsset(id string) (*model.Asset, error) {
    models,err := inst.findAsset("id = ?","",1,0,id)
    if err != nil {
        return nil,xerrors.Errorf("inst.findAsset() error: %w",err)
    }
    if len(models) == 0 {
        return nil,nil
    }
    return models[0],nil
}

//insert object
func (inst *Instance) InsertAsset(m *model.Asset, op Op) error {

    if err := inst.checkInsertAsset(m); err != nil {
        return xerrors.Errorf("checkInsertAsset() error: %w", err)
    }

    now := time.Now()
    id := op.GetOperationId()
    m.Created = now
    m.CreatedUser = id
    m.Created = now
    m.CreatedUser = id

    sql := "INSERT INTO assets (id,parent_id,name,detail,created_date,created_user,updated_date,updated_user) VALUES (?,?,?,?,?,?,?,?)"

    _,err := inst.run(sql,
           m.Id,m.ParentId,m.Name,m.Detail,m.Created,m.CreatedUser,m.Updated,m.UpdatedUser)
    if err != nil {
        return xerrors.Errorf("run() error: %w", err)
    }
    return nil
}

//check key
func (inst *Instance) checkInsertAsset(m *model.Asset) error {
    if inst.existAsset(m.Id) {
        return DuplicateKey
    }
    return nil
}

//find rows
func (inst *Instance) findAsset(where string,order string,limit int,offset int,args ...interface{}) ([]*model.Asset, error) {

	var base strings.Builder
    base.WriteString("SELECT id,parent_id,name,detail,DATETIME(created_date),created_user,DATETIME(updated_date),updated_user FROM assets")

    if where != "" {
        base.WriteString(" WHERE " + where)
    }
    if order != "" {
        base.WriteString(" ORDER BY " + order)
    }

    if limit > 0 {
        base.WriteString(fmt.Sprintf(" LIMIT %d", limit))
    }

    if offset > 0 {
        base.WriteString(fmt.Sprintf(" OFFSET %d", offset))
    }

    rows, err := inst.getRows(inst.ctx, base.String(),args...)
    if err != nil {
        return nil, xerrors.Errorf("getRows(Asset) error: %w", err)
    }

    models := make([]*model.Asset, 0)
    for rows.Next() {
        n, err := inst.createAsset(rows)
        if err != nil {
            return nil, xerrors.Errorf("createAsset() error: %w", err)
        } else if n == nil {
            break
        }
        models = append(models, n)
    }
    return models,nil
}

// create object 
func (inst *Instance) createAsset(row scanner) (*model.Asset, error) {

	var m model.Asset

    var id sql.NullString
    var parentId sql.NullString
    var name sql.NullString
    var detail sql.NullString
    var createdUser sql.NullString
    var updatedUser sql.NullString

	err := row.Scan(&id,&parentId,&name,&detail,&m.Created,&createdUser,&m.Updated,&updatedUser)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, xerrors.Errorf("Scan(Asset) error: %w", err)
		}
	}

    m.Id = to(id.String)
    m.ParentId = to(parentId.String)
    m.Name = to(name.String)
    m.Detail = to(detail.String)
    m.CreatedUser = to(createdUser.String)
    m.UpdatedUser = to(updatedUser.String)

	return &m, nil
}

// update row by key
func (inst *Instance) UpdateAsset(m *model.Asset,op Op) error {

    m.Updated = time.Now()
    m.UpdatedUser = op.GetOperationId()
    num,err := inst.updateAsset(
        "parent_id = ?,name = ?,detail = ?,updated_date = ?,updated_user = ?",
        "id = ?" ,from(m.ParentId),from(m.Name),from(m.Detail),m.Updated,from(m.UpdatedUser),from(m.Id))
    if err != nil {
        return xerrors.Errorf("updateAsset() error: %w", err)
    }
    if ( num != 1 ) {
        return xerrors.Errorf("update non single error: %v",m)
    }
    return nil
}

// update row 
func (inst *Instance) updateAsset(set string,where string,args ...interface{}) (int64,error) {
	var base strings.Builder
    base.WriteString("UPDATE assets SET")
    base.WriteString(" " + set + " ")
    if where != "" {
        base.WriteString(" WHERE " + where)
    }

    num,err := inst.run(base.String(), args...)
    if err != nil {
        return -1,xerrors.Errorf("run() error: %w", err)
    }
    return num,nil
}

//delete row by key
func (inst *Instance) DeleteAsset(id string) error {
    num,err := inst.deleteAsset("id = ?",from(id))
    if err != nil {
        return xerrors.Errorf("deleteAsset() error: %w", err)
    }
    if num != 1 {
        return fmt.Errorf("deleteAsset() non single error: %d", num)
    }
    return nil
}

// delete row 
func (inst *Instance) deleteAsset(where string,args ...interface{}) (int64,error) {

	var base strings.Builder
    base.WriteString("DELETE FROM assets")
    if where != "" {
        base.WriteString(" WHERE " + where)
    }

    num,err := inst.run(base.String(), args...)
    if err != nil {
        return -1,xerrors.Errorf("run() error: %w", err)
    }
    return num,nil
}

