// Code generated by db/model/config.go; DO NOT EDIT.
// 2024-10-01 08:03:19.0834523 +0900 JST m=+0.000000001 : { .Version }
package db

import (
	"database/sql"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"binder/db/model"

	"golang.org/x/xerrors"
)

const ConfigTableName = "config"

// create table
func createConfigTable(dir string) error {
	fn := filepath.Join(dir, tables["config"])
	err := createTableFile(fn, "name,detail,remote,marked_url,mermaid_url,created_date,created_user,updated_date,updated_user")
	if err != nil {
		return xerrors.Errorf("createTableFile() error: %w", err)
	}
	return nil
}

// exists check key
func (inst *Instance) existConfig() bool {
	m, err := inst.GetConfig()
	if err != nil || m == nil {
		return false
	}
	return true
}

// get row
func (inst *Instance) GetConfig() (*model.Config, error) {
	models, err := inst.findConfig("", "", 1, 0)
	if err != nil {
		return nil, xerrors.Errorf("inst.findConfig() error: %w", err)
	}
	if len(models) == 0 {
		return nil, newNotExistError("", "Config")
	}
	return models[0], nil
}

// insert object
func (inst *Instance) InsertConfig(m *model.Config, op Op) error {

	if err := inst.checkInsertConfig(m); err != nil {
		return xerrors.Errorf("checkInsertConfig() error: %w", err)
	}

	now := time.Now()
	id := op.GetOperationId()
	m.Created = now
	m.CreatedUser = id
	m.Created = now
	m.CreatedUser = id

	sql := "INSERT INTO config (name,detail,remote,marked_url,mermaid_url,created_date,created_user,updated_date,updated_user) VALUES (?,?,?,?,?,?,?,?,?)"

	_, err := inst.run(sql,
		m.Name, m.Detail, m.Remote, m.MarkedURL, m.MermaidURL, m.Created, m.CreatedUser, m.Updated, m.UpdatedUser)
	if err != nil {
		return xerrors.Errorf("run() error: %w", err)
	}
	return nil
}

// check key
func (inst *Instance) checkInsertConfig(m *model.Config) error {
	if inst.existConfig() {
		return DuplicateKey
	}
	return nil
}

// find rows
func (inst *Instance) findConfig(where string, order string, limit int, offset int, args ...interface{}) ([]*model.Config, error) {

	var base strings.Builder
	base.WriteString("SELECT name,detail,remote,marked_url,mermaid_url,DATETIME(created_date),created_user,DATETIME(updated_date),updated_user FROM config")

	if where != "" {
		base.WriteString(" WHERE " + where)
	}
	if order != "" {
		base.WriteString(" ORDER BY " + order)
	}

	if limit > 0 {
		base.WriteString(fmt.Sprintf(" LIMIT %d", limit))
	}

	if offset > 0 {
		base.WriteString(fmt.Sprintf(" OFFSET %d", offset))
	}

	sql := base.String()
	rows, err := inst.getRows(inst.ctx, sql, args...)
	if err != nil {
		return nil, xerrors.Errorf("getRows(Config) \n%s\n error: %w", sql, err)
	}

	models := make([]*model.Config, 0)
	for rows.Next() {
		n, err := inst.createConfig(rows)
		if err != nil {
			return nil, xerrors.Errorf("createConfig() error: %w", err)
		} else if n == nil {
			break
		}
		models = append(models, n)
	}
	return models, nil
}

// create object
func (inst *Instance) createConfig(row scanner) (*model.Config, error) {

	var m model.Config

	var name sql.NullString
	var detail sql.NullString
	var remote sql.NullString
	var markedURL sql.NullString
	var mermaidURL sql.NullString
	var createdUser sql.NullString
	var updatedUser sql.NullString

	err := row.Scan(&name, &detail, &remote, &markedURL, &mermaidURL, &m.Created, &createdUser, &m.Updated, &updatedUser)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, xerrors.Errorf("Scan(Config) error: %w", err)
		}
	}

	m.Name = to(name.String)
	m.Detail = to(detail.String)
	m.Remote = to(remote.String)
	m.MarkedURL = to(markedURL.String)
	m.MermaidURL = to(mermaidURL.String)
	m.CreatedUser = to(createdUser.String)
	m.UpdatedUser = to(updatedUser.String)

	return &m, nil
}

// update row by key
func (inst *Instance) UpdateConfig(m *model.Config, op Op) error {

	m.Updated = time.Now()
	m.UpdatedUser = op.GetOperationId()
	num, err := inst.updateConfig(
		"name = ?,detail = ?,remote = ?,marked_url = ?,mermaid_url = ?,updated_date = ?,updated_user = ?",
		"", from(m.Name), from(m.Detail), from(m.Remote), from(m.MarkedURL), from(m.MermaidURL), m.Updated, from(m.UpdatedUser))
	if err != nil {
		return xerrors.Errorf("updateConfig() error: %w", err)
	}
	if num != 1 {
		return xerrors.Errorf("update non single error: %v", m)
	}
	return nil
}

// update row
func (inst *Instance) updateConfig(set string, where string, args ...interface{}) (int64, error) {
	var base strings.Builder
	base.WriteString("UPDATE config SET")
	base.WriteString(" " + set + " ")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}

// delete row by key
func (inst *Instance) DeleteConfig() error {
	num, err := inst.deleteConfig("")
	if err != nil {
		return xerrors.Errorf("deleteConfig() error: %w", err)
	}
	if num != 1 {
		return fmt.Errorf("deleteConfig() non single error: %d", num)
	}
	return nil
}

// delete row
func (inst *Instance) deleteConfig(where string, args ...interface{}) (int64, error) {

	var base strings.Builder
	base.WriteString("DELETE FROM config")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}
