// Code generated by model/diagram.go; DO NOT EDIT.
// 2024-09-22 08:06:05.373599 +0900 JST m=+0.014954701
package db

import (
    "database/sql"
    "errors"
    "fmt"
    "path/filepath"
    "strings"
    "time"

    "binder/db/model"

	"golang.org/x/xerrors"
)

// create table
func createDiagramTable(dir string) (string,error) {
    fn := filepath.Join(dir,"diagrams.csv")
    err := createTableFile(fn,"id,parent_id,alias,name,detail,publish_date,created_date,created_user,updated_date,updated_user")
    if err != nil {
      return "",xerrors.Errorf("createTableFile() error: %w",err)
    }
    return fn,nil
}

// exists check key
func (inst *Instance) existDiagram(id string) bool {
    m,err := inst.GetDiagram(id)
    if err != nil || m == nil {
        return false
    }
    return true
}

// get row 
func (inst *Instance) GetDiagram(id string) (*model.Diagram, error) {
    models,err := inst.findDiagram("id = ?","",1,0,id)
    if err != nil {
        return nil,xerrors.Errorf("inst.findDiagram() error: %w",err)
    }
    if len(models) == 0 {
        return nil,nil
    }
    return models[0],nil
}

//insert object
func (inst *Instance) InsertDiagram(m *model.Diagram, op Op) error {

    if err := inst.checkInsertDiagram(m); err != nil {
        return xerrors.Errorf("checkInsertDiagram() error: %w", err)
    }

    now := time.Now()
    id := op.GetOperationId()
    m.Created = now
    m.CreatedUser = id
    m.Created = now
    m.CreatedUser = id

    sql := "INSERT INTO diagrams (id,parent_id,alias,name,detail,publish_date,created_date,created_user,updated_date,updated_user) VALUES (?,?,?,?,?,?,?,?,?,?)"

    _,err := inst.run(sql,
           m.Id,m.ParentId,m.Alias,m.Name,m.Detail,m.Publish,m.Created,m.CreatedUser,m.Updated,m.UpdatedUser)
    if err != nil {
        return xerrors.Errorf("run() error: %w", err)
    }
    return nil
}

//check key
func (inst *Instance) checkInsertDiagram(m *model.Diagram) error {
    if inst.existDiagram(m.Id) {
        return DuplicateKey
    }
    return nil
}

//find rows
func (inst *Instance) findDiagram(where string,order string,limit int,offset int,args ...interface{}) ([]*model.Diagram, error) {

	var base strings.Builder
    base.WriteString("SELECT id,parent_id,alias,name,detail,DATETIME(publish_date),DATETIME(created_date),created_user,DATETIME(updated_date),updated_user FROM diagrams")

    if where != "" {
        base.WriteString(" WHERE " + where)
    }
    if order != "" {
        base.WriteString(" ORDER BY " + order)
    }

    if limit > 0 {
        base.WriteString(fmt.Sprintf(" LIMIT %d", limit))
    }

    if offset > 0 {
        base.WriteString(fmt.Sprintf(" OFFSET %d", offset))
    }

    rows, err := inst.getRows(inst.ctx, base.String(),args...)
    if err != nil {
        return nil, xerrors.Errorf("getRows(Diagram) error: %w", err)
    }

    models := make([]*model.Diagram, 0)
    for rows.Next() {
        n, err := inst.createDiagram(rows)
        if err != nil {
            return nil, xerrors.Errorf("createDiagram() error: %w", err)
        } else if n == nil {
            break
        }
        models = append(models, n)
    }
    return models,nil
}

// create object 
func (inst *Instance) createDiagram(row scanner) (*model.Diagram, error) {

	var m model.Diagram

    var id sql.NullString
    var parentId sql.NullString
    var alias sql.NullString
    var name sql.NullString
    var detail sql.NullString
    var createdUser sql.NullString
    var updatedUser sql.NullString

	err := row.Scan(&id,&parentId,&alias,&name,&detail,&m.Publish,&m.Created,&createdUser,&m.Updated,&updatedUser)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, xerrors.Errorf("Scan(Diagram) error: %w", err)
		}
	}

    m.Id = to(id.String)
    m.ParentId = to(parentId.String)
    m.Alias = to(alias.String)
    m.Name = to(name.String)
    m.Detail = to(detail.String)
    m.CreatedUser = to(createdUser.String)
    m.UpdatedUser = to(updatedUser.String)

	return &m, nil
}

// update row by key
func (inst *Instance) UpdateDiagram(m *model.Diagram,op Op) error {

    m.Updated = time.Now()
    m.UpdatedUser = op.GetOperationId()
    num,err := inst.updateDiagram(
        "parent_id = ?,alias = ?,name = ?,detail = ?,publish_date = ?,updated_date = ?,updated_user = ?",
        "id = ?" ,from(m.ParentId),from(m.Alias),from(m.Name),from(m.Detail),m.Publish,m.Updated,from(m.UpdatedUser),from(m.Id))
    if err != nil {
        return xerrors.Errorf("updateDiagram() error: %w", err)
    }
    if ( num != 1 ) {
        return xerrors.Errorf("update non single error: %v",m)
    }
    return nil
}

// update row 
func (inst *Instance) updateDiagram(set string,where string,args ...interface{}) (int64,error) {
	var base strings.Builder
    base.WriteString("UPDATE diagrams SET")
    base.WriteString(" " + set + " ")
    if where != "" {
        base.WriteString(" WHERE " + where)
    }

    num,err := inst.run(base.String(), args...)
    if err != nil {
        return -1,xerrors.Errorf("run() error: %w", err)
    }
    return num,nil
}

//delete row by key
func (inst *Instance) DeleteDiagram(id string) error {
    num,err := inst.deleteDiagram("id = ?",from(id))
    if err != nil {
        return xerrors.Errorf("deleteDiagram() error: %w", err)
    }
    if num != 1 {
        return fmt.Errorf("deleteDiagram() non single error: %d", num)
    }
    return nil
}

// delete row 
func (inst *Instance) deleteDiagram(where string,args ...interface{}) (int64,error) {

	var base strings.Builder
    base.WriteString("DELETE FROM diagrams")
    if where != "" {
        base.WriteString(" WHERE " + where)
    }

    num,err := inst.run(base.String(), args...)
    if err != nil {
        return -1,xerrors.Errorf("run() error: %w", err)
    }
    return num,nil
}

