// Code generated by db/model/layer.go; DO NOT EDIT.
// 2026-04-22 06:16:01.868267 +0900 JST m=+0.078328301 : { .Version }
package db

import (
	"database/sql"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"binder/db/model"

	"golang.org/x/xerrors"
)

const LayerTableName = "layers"

// create table
func createLayerTable(dir string) error {
	fn := filepath.Join(dir, tables["layers"])
	err := createTableFile(fn, "id,created_date,created_user,updated_date,updated_user")
	if err != nil {
		return xerrors.Errorf("createTableFile() error: %w", err)
	}
	return nil
}

// exists check key
func (inst *Instance) existLayer(id string) bool {
	m, err := inst.GetLayer(id)
	if err != nil || m == nil {
		return false
	}
	return true
}

// get row
func (inst *Instance) GetLayer(id string) (*model.Layer, error) {
	models, err := inst.findLayer("id = ?", "", 1, 0, id)
	if err != nil {
		return nil, xerrors.Errorf("inst.findLayer() error: %w", err)
	}
	if len(models) == 0 {
		return nil, newNotExistError(id, "Layer")
	}
	return models[0], nil
}

// insert object
func (inst *Instance) InsertLayer(m *model.Layer, op Op) error {

	if err := inst.checkInsertLayer(m); err != nil {
		return xerrors.Errorf("checkInsertLayer() error: %w", err)
	}

	now := time.Now()
	id := op.GetOperationId()
	m.Created = now
	m.CreatedUser = id
	m.Created = now
	m.CreatedUser = id

	sql := "INSERT INTO layers (id,created_date,created_user,updated_date,updated_user) VALUES (?,?,?,?,?)"

	_, err := inst.run(sql,
		m.Id, m.Created, m.CreatedUser, m.Updated, m.UpdatedUser)
	if err != nil {
		return xerrors.Errorf("run() error: %w", err)
	}
	return nil
}

// check key
func (inst *Instance) checkInsertLayer(m *model.Layer) error {
	if inst.existLayer(m.Id) {
		return DuplicateKey
	}
	return nil
}

// find rows
func (inst *Instance) findLayer(where string, order string, limit int, offset int, args ...interface{}) ([]*model.Layer, error) {

	var base strings.Builder
	base.WriteString("SELECT id,DATETIME(created_date),created_user,DATETIME(updated_date),updated_user FROM layers")

	if where != "" {
		base.WriteString(" WHERE " + where)
	}
	if order != "" {
		base.WriteString(" ORDER BY " + order)
	}

	if limit > 0 {
		base.WriteString(fmt.Sprintf(" LIMIT %d", limit))
	}

	if offset > 0 {
		base.WriteString(fmt.Sprintf(" OFFSET %d", offset))
	}

	sql := base.String()
	rows, err := inst.getRows(inst.ctx, sql, args...)
	if err != nil {
		return nil, xerrors.Errorf("getRows(Layer) \n%s\n error: %w", sql, err)
	}

	models := make([]*model.Layer, 0)
	for rows.Next() {
		n, err := inst.createLayer(rows)
		if err != nil {
			return nil, xerrors.Errorf("createLayer() error: %w", err)
		} else if n == nil {
			break
		}
		models = append(models, n)
	}
	return models, nil
}

// create object
func (inst *Instance) createLayer(row scanner) (*model.Layer, error) {

	var m model.Layer

	var id sql.NullString
	var createdUser sql.NullString
	var updatedUser sql.NullString

	err := row.Scan(&id, &m.Created, &createdUser, &m.Updated, &updatedUser)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, xerrors.Errorf("Scan(Layer) error: %w", err)
		}
	}

	m.Id = to(id.String)
	m.CreatedUser = to(createdUser.String)
	m.UpdatedUser = to(updatedUser.String)

	return &m, nil
}

// update row by key
func (inst *Instance) UpdateLayer(m *model.Layer, op Op) error {

	m.Updated = time.Now()
	m.UpdatedUser = op.GetOperationId()
	num, err := inst.updateLayer(
		"updated_date = ?,updated_user = ?",
		"id = ?", m.Updated, from(m.UpdatedUser), from(m.Id))
	if err != nil {
		return xerrors.Errorf("updateLayer() error: %w", err)
	}
	if num != 1 {
		return xerrors.Errorf("update non single error: %v", m)
	}
	return nil
}

// update row
func (inst *Instance) updateLayer(set string, where string, args ...interface{}) (int64, error) {
	var base strings.Builder
	base.WriteString("UPDATE layers SET")
	base.WriteString(" " + set + " ")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}

// delete row by key
func (inst *Instance) DeleteLayer(id string) error {
	num, err := inst.deleteLayer("id = ?", from(id))
	if err != nil {
		return xerrors.Errorf("deleteLayer() error: %w", err)
	}
	if num != 1 {
		return fmt.Errorf("deleteLayer() non single error: %d", num)
	}
	return nil
}

// delete row
func (inst *Instance) deleteLayer(where string, args ...interface{}) (int64, error) {

	var base strings.Builder
	base.WriteString("DELETE FROM layers")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}
