// Code generated by db/model/note.go; DO NOT EDIT.
// 2026-03-12 06:09:24.2886307 +0900 JST m=+0.000529801 : { .Version }
package db

import (
	"database/sql"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"binder/db/model"

	"golang.org/x/xerrors"
)

const NoteTableName = "notes"

// create table
func createNoteTable(dir string) error {
	fn := filepath.Join(dir, tables["notes"])
	err := createTableFile(fn, "id,layout_template,content_template,created_date,created_user,updated_date,updated_user")
	if err != nil {
		return xerrors.Errorf("createTableFile() error: %w", err)
	}
	return nil
}

// exists check key
func (inst *Instance) existNote(id string) bool {
	m, err := inst.GetNote(id)
	if err != nil || m == nil {
		return false
	}
	return true
}

// get row
func (inst *Instance) GetNote(id string) (*model.Note, error) {
	models, err := inst.findNote("id = ?", "", 1, 0, id)
	if err != nil {
		return nil, xerrors.Errorf("inst.findNote() error: %w", err)
	}
	if len(models) == 0 {
		return nil, newNotExistError(id, "Note")
	}
	return models[0], nil
}

// insert object
func (inst *Instance) InsertNote(m *model.Note, op Op) error {

	if err := inst.checkInsertNote(m); err != nil {
		return xerrors.Errorf("checkInsertNote() error: %w", err)
	}

	now := time.Now()
	id := op.GetOperationId()
	m.Created = now
	m.CreatedUser = id
	m.Created = now
	m.CreatedUser = id

	sql := "INSERT INTO notes (id,layout_template,content_template,created_date,created_user,updated_date,updated_user) VALUES (?,?,?,?,?,?,?)"

	_, err := inst.run(sql,
		m.Id, m.LayoutTemplate, m.ContentTemplate, m.Created, m.CreatedUser, m.Updated, m.UpdatedUser)
	if err != nil {
		return xerrors.Errorf("run() error: %w", err)
	}
	return nil
}

// check key
func (inst *Instance) checkInsertNote(m *model.Note) error {
	if inst.existNote(m.Id) {
		return DuplicateKey
	}
	return nil
}

// find rows
func (inst *Instance) findNote(where string, order string, limit int, offset int, args ...interface{}) ([]*model.Note, error) {

	var base strings.Builder
	base.WriteString("SELECT id,layout_template,content_template,DATETIME(created_date),created_user,DATETIME(updated_date),updated_user FROM notes")

	if where != "" {
		base.WriteString(" WHERE " + where)
	}
	if order != "" {
		base.WriteString(" ORDER BY " + order)
	}

	if limit > 0 {
		base.WriteString(fmt.Sprintf(" LIMIT %d", limit))
	}

	if offset > 0 {
		base.WriteString(fmt.Sprintf(" OFFSET %d", offset))
	}

	sql := base.String()
	rows, err := inst.getRows(inst.ctx, sql, args...)
	if err != nil {
		return nil, xerrors.Errorf("getRows(Note) \n%s\n error: %w", sql, err)
	}

	models := make([]*model.Note, 0)
	for rows.Next() {
		n, err := inst.createNote(rows)
		if err != nil {
			return nil, xerrors.Errorf("createNote() error: %w", err)
		} else if n == nil {
			break
		}
		models = append(models, n)
	}
	return models, nil
}

// create object
func (inst *Instance) createNote(row scanner) (*model.Note, error) {

	var m model.Note

	var id sql.NullString
	var layoutTemplate sql.NullString
	var contentTemplate sql.NullString
	var createdUser sql.NullString
	var updatedUser sql.NullString

	err := row.Scan(&id, &layoutTemplate, &contentTemplate, &m.Created, &createdUser, &m.Updated, &updatedUser)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, xerrors.Errorf("Scan(Note) error: %w", err)
		}
	}

	m.Id = to(id.String)
	m.LayoutTemplate = to(layoutTemplate.String)
	m.ContentTemplate = to(contentTemplate.String)
	m.CreatedUser = to(createdUser.String)
	m.UpdatedUser = to(updatedUser.String)

	return &m, nil
}

// update row by key
func (inst *Instance) UpdateNote(m *model.Note, op Op) error {

	m.Updated = time.Now()
	m.UpdatedUser = op.GetOperationId()
	num, err := inst.updateNote(
		"layout_template = ?,content_template = ?,updated_date = ?,updated_user = ?",
		"id = ?", from(m.LayoutTemplate), from(m.ContentTemplate), m.Updated, from(m.UpdatedUser), from(m.Id))
	if err != nil {
		return xerrors.Errorf("updateNote() error: %w", err)
	}
	if num != 1 {
		return xerrors.Errorf("update non single error: %v", m)
	}
	return nil
}

// update row
func (inst *Instance) updateNote(set string, where string, args ...interface{}) (int64, error) {
	var base strings.Builder
	base.WriteString("UPDATE notes SET")
	base.WriteString(" " + set + " ")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}

// delete row by key
func (inst *Instance) DeleteNote(id string) error {
	num, err := inst.deleteNote("id = ?", from(id))
	if err != nil {
		return xerrors.Errorf("deleteNote() error: %w", err)
	}
	if num != 1 {
		return fmt.Errorf("deleteNote() non single error: %d", num)
	}
	return nil
}

// delete row
func (inst *Instance) deleteNote(where string, args ...interface{}) (int64, error) {

	var base strings.Builder
	base.WriteString("DELETE FROM notes")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}
