// Code generated by db/model/structure.go; DO NOT EDIT.
// 2026-04-07 08:43:36.5136681 +0900 JST m=+0.037789801 : { .Version }
package db

import (
	"database/sql"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"binder/db/model"

	"golang.org/x/xerrors"
)

const StructureTableName = "structures"

// create table
func createStructureTable(dir string) error {
	fn := filepath.Join(dir, tables["structures"])
	err := createTableFile(fn, "id,parent_id,seq,type,name,detail,alias,publish_date,republish_date,private,created_date,created_user,updated_date,updated_user")
	if err != nil {
		return xerrors.Errorf("createTableFile() error: %w", err)
	}
	return nil
}

// exists check key
func (inst *Instance) existStructure(id string) bool {
	m, err := inst.GetStructure(id)
	if err != nil || m == nil {
		return false
	}
	return true
}

// get row
func (inst *Instance) GetStructure(id string) (*model.Structure, error) {
	models, err := inst.findStructure("id = ?", "", 1, 0, id)
	if err != nil {
		return nil, xerrors.Errorf("inst.findStructure() error: %w", err)
	}
	if len(models) == 0 {
		return nil, newNotExistError(id, "Structure")
	}
	return models[0], nil
}

// insert object
func (inst *Instance) InsertStructure(m *model.Structure, op Op) error {

	if err := inst.checkInsertStructure(m); err != nil {
		return xerrors.Errorf("checkInsertStructure() error: %w", err)
	}

	now := time.Now()
	id := op.GetOperationId()
	m.Created = now
	m.CreatedUser = id
	m.Created = now
	m.CreatedUser = id

	sql := "INSERT INTO structures (id,parent_id,seq,type,name,detail,alias,publish_date,republish_date,private,created_date,created_user,updated_date,updated_user) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)"

	_, err := inst.run(sql,
		m.Id, m.ParentId, m.Seq, m.Typ, m.Name, m.Detail, m.Alias, m.Publish, m.Republish, m.Private, m.Created, m.CreatedUser, m.Updated, m.UpdatedUser)
	if err != nil {
		return xerrors.Errorf("run() error: %w", err)
	}
	return nil
}

// check key
func (inst *Instance) checkInsertStructure(m *model.Structure) error {
	if inst.existStructure(m.Id) {
		return DuplicateKey
	}
	return nil
}

// find rows
func (inst *Instance) findStructure(where string, order string, limit int, offset int, args ...interface{}) ([]*model.Structure, error) {

	var base strings.Builder
	base.WriteString("SELECT id,parent_id,seq,type,name,detail,alias,DATETIME(publish_date),DATETIME(republish_date),private,DATETIME(created_date),created_user,DATETIME(updated_date),updated_user FROM structures")

	if where != "" {
		base.WriteString(" WHERE " + where)
	}
	if order != "" {
		base.WriteString(" ORDER BY " + order)
	}

	if limit > 0 {
		base.WriteString(fmt.Sprintf(" LIMIT %d", limit))
	}

	if offset > 0 {
		base.WriteString(fmt.Sprintf(" OFFSET %d", offset))
	}

	sql := base.String()
	rows, err := inst.getRows(inst.ctx, sql, args...)
	if err != nil {
		return nil, xerrors.Errorf("getRows(Structure) \n%s\n error: %w", sql, err)
	}

	models := make([]*model.Structure, 0)
	for rows.Next() {
		n, err := inst.createStructure(rows)
		if err != nil {
			return nil, xerrors.Errorf("createStructure() error: %w", err)
		} else if n == nil {
			break
		}
		models = append(models, n)
	}
	return models, nil
}

// create object
func (inst *Instance) createStructure(row scanner) (*model.Structure, error) {

	var m model.Structure

	var id sql.NullString
	var parentId sql.NullString
	var typ sql.NullString
	var name sql.NullString
	var detail sql.NullString
	var alias sql.NullString
	var createdUser sql.NullString
	var updatedUser sql.NullString

	err := row.Scan(&id, &parentId, &m.Seq, &typ, &name, &detail, &alias, &m.Publish, &m.Republish, &m.Private, &m.Created, &createdUser, &m.Updated, &updatedUser)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, xerrors.Errorf("Scan(Structure) error: %w", err)
		}
	}

	m.Id = to(id.String)
	m.ParentId = to(parentId.String)
	m.Typ = to(typ.String)
	m.Name = to(name.String)
	m.Detail = to(detail.String)
	m.Alias = to(alias.String)
	m.CreatedUser = to(createdUser.String)
	m.UpdatedUser = to(updatedUser.String)

	return &m, nil
}

// update row by key
func (inst *Instance) UpdateStructure(m *model.Structure, op Op) error {

	m.Updated = time.Now()
	m.UpdatedUser = op.GetOperationId()
	num, err := inst.updateStructure(
		"parent_id = ?,seq = ?,type = ?,name = ?,detail = ?,alias = ?,publish_date = ?,republish_date = ?,private = ?,updated_date = ?,updated_user = ?",
		"id = ?", from(m.ParentId), m.Seq, from(m.Typ), from(m.Name), from(m.Detail), from(m.Alias), m.Publish, m.Republish, m.Private, m.Updated, from(m.UpdatedUser), from(m.Id))
	if err != nil {
		return xerrors.Errorf("updateStructure() error: %w", err)
	}
	if num != 1 {
		return xerrors.Errorf("update non single error: %v", m)
	}
	return nil
}

// update row
func (inst *Instance) updateStructure(set string, where string, args ...interface{}) (int64, error) {
	var base strings.Builder
	base.WriteString("UPDATE structures SET")
	base.WriteString(" " + set + " ")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}

// delete row by key
func (inst *Instance) DeleteStructure(id string) error {
	num, err := inst.deleteStructure("id = ?", from(id))
	if err != nil {
		return xerrors.Errorf("deleteStructure() error: %w", err)
	}
	if num != 1 {
		return fmt.Errorf("deleteStructure() non single error: %d", num)
	}
	return nil
}

// delete row
func (inst *Instance) deleteStructure(where string, args ...interface{}) (int64, error) {

	var base strings.Builder
	base.WriteString("DELETE FROM structures")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}
