// Code generated by db/model/template.go; DO NOT EDIT.
// 2026-04-07 08:43:36.5110696 +0900 JST m=+0.035191301 : { .Version }
package db

import (
	"database/sql"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"binder/db/model"

	"golang.org/x/xerrors"
)

const TemplateTableName = "templates"

// create table
func createTemplateTable(dir string) error {
	fn := filepath.Join(dir, tables["templates"])
	err := createTableFile(fn, "id,type,name,detail,seq,created_date,created_user,updated_date,updated_user")
	if err != nil {
		return xerrors.Errorf("createTableFile() error: %w", err)
	}
	return nil
}

// exists check key
func (inst *Instance) existTemplate(id string) bool {
	m, err := inst.GetTemplate(id)
	if err != nil || m == nil {
		return false
	}
	return true
}

// get row
func (inst *Instance) GetTemplate(id string) (*model.Template, error) {
	models, err := inst.findTemplate("id = ?", "", 1, 0, id)
	if err != nil {
		return nil, xerrors.Errorf("inst.findTemplate() error: %w", err)
	}
	if len(models) == 0 {
		return nil, newNotExistError(id, "Template")
	}
	return models[0], nil
}

// insert object
func (inst *Instance) InsertTemplate(m *model.Template, op Op) error {

	if err := inst.checkInsertTemplate(m); err != nil {
		return xerrors.Errorf("checkInsertTemplate() error: %w", err)
	}

	now := time.Now()
	id := op.GetOperationId()
	m.Created = now
	m.CreatedUser = id
	m.Created = now
	m.CreatedUser = id

	sql := "INSERT INTO templates (id,type,name,detail,seq,created_date,created_user,updated_date,updated_user) VALUES (?,?,?,?,?,?,?,?,?)"

	_, err := inst.run(sql,
		m.Id, m.Typ, m.Name, m.Detail, m.Seq, m.Created, m.CreatedUser, m.Updated, m.UpdatedUser)
	if err != nil {
		return xerrors.Errorf("run() error: %w", err)
	}
	return nil
}

// check key
func (inst *Instance) checkInsertTemplate(m *model.Template) error {
	if inst.existTemplate(m.Id) {
		return DuplicateKey
	}
	return nil
}

// find rows
func (inst *Instance) findTemplate(where string, order string, limit int, offset int, args ...interface{}) ([]*model.Template, error) {

	var base strings.Builder
	base.WriteString("SELECT id,type,name,detail,seq,DATETIME(created_date),created_user,DATETIME(updated_date),updated_user FROM templates")

	if where != "" {
		base.WriteString(" WHERE " + where)
	}
	if order != "" {
		base.WriteString(" ORDER BY " + order)
	}

	if limit > 0 {
		base.WriteString(fmt.Sprintf(" LIMIT %d", limit))
	}

	if offset > 0 {
		base.WriteString(fmt.Sprintf(" OFFSET %d", offset))
	}

	sql := base.String()
	rows, err := inst.getRows(inst.ctx, sql, args...)
	if err != nil {
		return nil, xerrors.Errorf("getRows(Template) \n%s\n error: %w", sql, err)
	}

	models := make([]*model.Template, 0)
	for rows.Next() {
		n, err := inst.createTemplate(rows)
		if err != nil {
			return nil, xerrors.Errorf("createTemplate() error: %w", err)
		} else if n == nil {
			break
		}
		models = append(models, n)
	}
	return models, nil
}

// create object
func (inst *Instance) createTemplate(row scanner) (*model.Template, error) {

	var m model.Template

	var id sql.NullString
	var typ sql.NullString
	var name sql.NullString
	var detail sql.NullString
	var createdUser sql.NullString
	var updatedUser sql.NullString

	err := row.Scan(&id, &typ, &name, &detail, &m.Seq, &m.Created, &createdUser, &m.Updated, &updatedUser)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		} else {
			return nil, xerrors.Errorf("Scan(Template) error: %w", err)
		}
	}

	m.Id = to(id.String)
	m.Typ = to(typ.String)
	m.Name = to(name.String)
	m.Detail = to(detail.String)
	m.CreatedUser = to(createdUser.String)
	m.UpdatedUser = to(updatedUser.String)

	return &m, nil
}

// update row by key
func (inst *Instance) UpdateTemplate(m *model.Template, op Op) error {

	m.Updated = time.Now()
	m.UpdatedUser = op.GetOperationId()
	num, err := inst.updateTemplate(
		"type = ?,name = ?,detail = ?,seq = ?,updated_date = ?,updated_user = ?",
		"id = ?", from(m.Typ), from(m.Name), from(m.Detail), m.Seq, m.Updated, from(m.UpdatedUser), from(m.Id))
	if err != nil {
		return xerrors.Errorf("updateTemplate() error: %w", err)
	}
	if num != 1 {
		return xerrors.Errorf("update non single error: %v", m)
	}
	return nil
}

// update row
func (inst *Instance) updateTemplate(set string, where string, args ...interface{}) (int64, error) {
	var base strings.Builder
	base.WriteString("UPDATE templates SET")
	base.WriteString(" " + set + " ")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}

// delete row by key
func (inst *Instance) DeleteTemplate(id string) error {
	num, err := inst.deleteTemplate("id = ?", from(id))
	if err != nil {
		return xerrors.Errorf("deleteTemplate() error: %w", err)
	}
	if num != 1 {
		return fmt.Errorf("deleteTemplate() non single error: %d", num)
	}
	return nil
}

// delete row
func (inst *Instance) deleteTemplate(where string, args ...interface{}) (int64, error) {

	var base strings.Builder
	base.WriteString("DELETE FROM templates")
	if where != "" {
		base.WriteString(" WHERE " + where)
	}

	num, err := inst.run(base.String(), args...)
	if err != nil {
		return -1, xerrors.Errorf("run() error: %w", err)
	}
	return num, nil
}
