// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * wailsRuntime は api.AppRuntime の Wails v3 実装。
 * Wails v3 の依存はこの構造体および main() 内に閉じており、
 * ルートの binder パッケージには持ち込まない。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenBinderSite() {
    return $Call.ByID(3871029567);
}

/**
 * @param {boolean} create
 * @param {string} defaultDir
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog(create, defaultDir) {
    return $Call.ByID(182410494, create, defaultDir);
}

/**
 * @param {string} name
 * @param {string} ptn
 * @returns {$CancellablePromise<string>}
 */
export function OpenFilePicker(name, ptn) {
    return $Call.ByID(32503012, name, ptn);
}

/**
 * @param {string} typ
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function OpenHistoryWindow(typ, id) {
    return $Call.ByID(3809821628, typ, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenModifiedWindow() {
    return $Call.ByID(2614306599);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(1541717289, url);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(4019951503);
}

/**
 * setting.go
 * @returns {$CancellablePromise<void>}
 */
export function SavePosition() {
    return $Call.ByID(3402270882);
}

/**
 * @param {boolean} create
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(create) {
    return $Call.ByID(3306293051, create);
}

/**
 * @param {string} name
 * @param {string} ptn
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile(name, ptn) {
    return $Call.ByID(2323880782, name, ptn);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function Terminate() {
    return $Call.ByID(248879631);
}

/**
 * @returns {$CancellablePromise<[number, number]>}
 */
export function WindowPosition() {
    return $Call.ByID(175003119);
}

/**
 * @returns {$CancellablePromise<[number, number]>}
 */
export function WindowSize() {
    return $Call.ByID(1890613829);
}
