version: '3'

includes:
  common: ./build/Taskfile.yml

vars:
  APP_NAME: "binder-lite"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9246}}'

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "common:build"

  run:
    summary: Runs the application
    cmds:
      - task: "common:run"

  dev:
    summary: Runs the application in development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
