// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Binder {
    /**
     * Creates a new Binder instance.
     * @param {Partial<Binder>} [$$source = {}] - The source object to create the Binder.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Binder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Binder}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Binder(/** @type {Partial<Binder>} */($$parsedSource));
    }
}

export class Patch {
    /**
     * Creates a new Patch instance.
     * @param {Partial<Patch>} [$$source = {}] - The source object to create the Patch.
     */
    constructor($$source = {}) {
        if (!("patch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["patch"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Patch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Patch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Patch(/** @type {Partial<Patch>} */($$parsedSource));
    }
}
