// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Snippet は単一のスニペット項目
 */
export class Snippet {
    /**
     * Creates a new Snippet instance.
     * @param {Partial<Snippet>} [$$source = {}] - The source object to create the Snippet.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippet}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snippet(/** @type {Partial<Snippet>} */($$parsedSource));
    }
}

/**
 * Snippets はsnippets.jsonのルート構造
 */
export class Snippets {
    /**
     * Creates a new Snippets instance.
     * @param {Partial<Snippets>} [$$source = {}] - The source object to create the Snippets.
     */
    constructor($$source = {}) {
        if (!("markdowns" in $$source)) {
            /**
             * @member
             * @type {Snippet[]}
             */
            this["markdowns"] = [];
        }
        if (!("diagrams" in $$source)) {
            /**
             * @member
             * @type {Snippet[]}
             */
            this["diagrams"] = [];
        }
        if (!("templates" in $$source)) {
            /**
             * @member
             * @type {Snippet[]}
             */
            this["templates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippets instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippets}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("markdowns" in $$parsedSource) {
            $$parsedSource["markdowns"] = $$createField0_0($$parsedSource["markdowns"]);
        }
        if ("diagrams" in $$parsedSource) {
            $$parsedSource["diagrams"] = $$createField1_0($$parsedSource["diagrams"]);
        }
        if ("templates" in $$parsedSource) {
            $$parsedSource["templates"] = $$createField2_0($$parsedSource["templates"]);
        }
        return new Snippets(/** @type {Partial<Snippets>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Snippet.createFrom;
const $$createType1 = $Create.Array($$createType0);
