name: Multi-OS Echo Test

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
env:

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  echo-test:
    if: github.event.pull_request.merged == true
    # ここから下がジョブの設定（stepsと同階層）
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    # 実行するOSの指定（matrixを参照）
    runs-on: ${{ matrix.os }}

    # 実際の実行手順
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            webkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Get Go Env
        shell: bash
        run: |
          echo "GOOS=$(go env GOOS)" >> $GITHUB_ENV
          echo "GOARCH=$(go env GOARCH)" >> $GITHUB_ENV
          echo "APP_NAME=binder" >> $GITHUB_ENV
          echo "VERSION=0.9.2" >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Display version
        run: |
          go version
          go env GOOS GOARCH
          node -v
          npm -v

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest

      - name: Wails doctor
        run: |
          wails3 version
          wails3 doctor

      - name: Build or Package
        working-directory: ./_cmd/binder
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            wails3 package
          else
            wails3 build
          fi

      - name: Archive Build Results
        shell: bash
        run: |
          export GOOS=$(go env GOOS)
          export GOARCH=$(go env GOARCH)
          export ZIP_NAME="binder-${VERSION}_${GOOS}_${GOARCH}.zip"
          cd ./_cmd/binder/bin
          if [ "${{ runner.os }}" = "Windows" ]; then
            7z a ../../../${ZIP_NAME} ./*
          else
            zip -r ../../../${ZIP_NAME} ./*
          fi
          echo "ZIP_PATH=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-asset
          path: ${{ env.ZIP_PATH }}
