// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Editor {
    /**
     * Creates a new Editor instance.
     * @param {Partial<Editor>} [$$source = {}] - The source object to create the Editor.
     */
    constructor($$source = {}) {
        if (!("program" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["program"] = "";
        }
        if (!("GitBash" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["GitBash"] = false;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {Font | null}
             */
            this["text"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Editor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Editor}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("text" in $$parsedSource) {
            $$parsedSource["text"] = $$createField2_0($$parsedSource["text"]);
        }
        return new Editor(/** @type {Partial<Editor>} */($$parsedSource));
    }
}

export class Font {
    /**
     * Creates a new Font instance.
     * @param {Partial<Font>} [$$source = {}] - The source object to create the Font.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("backgroundColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backgroundColor"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Font instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Font}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Font(/** @type {Partial<Font>} */($$parsedSource));
    }
}

export class Git {
    /**
     * Creates a new Git instance.
     * @param {Partial<Git>} [$$source = {}] - The source object to create the Git.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("mail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mail"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("File" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["File"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Git instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Git}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Git(/** @type {Partial<Git>} */($$parsedSource));
    }
}

export class Look {
    /**
     * Creates a new Look instance.
     * @param {Partial<Look>} [$$source = {}] - The source object to create the Look.
     */
    constructor($$source = {}) {
        if (!("darkMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["darkMode"] = false;
        }
        if (!("whole" in $$source)) {
            /**
             * @member
             * @type {Font | null}
             */
            this["whole"] = null;
        }
        if (!("treeNoteNum" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["treeNoteNum"] = 0;
        }
        if (!("editor" in $$source)) {
            /**
             * @member
             * @type {Editor | null}
             */
            this["editor"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Look instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Look}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("whole" in $$parsedSource) {
            $$parsedSource["whole"] = $$createField1_0($$parsedSource["whole"]);
        }
        if ("editor" in $$parsedSource) {
            $$parsedSource["editor"] = $$createField3_0($$parsedSource["editor"]);
        }
        return new Look(/** @type {Partial<Look>} */($$parsedSource));
    }
}

export class Path {
    /**
     * Creates a new Path instance.
     * @param {Partial<Path>} [$$source = {}] - The source object to create the Path.
     */
    constructor($$source = {}) {
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("runWithOpen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["runWithOpen"] = false;
        }
        if (!("openWithItem" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["openWithItem"] = false;
        }
        if (!("histories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["histories"] = [];
        }
        if (!("lastNoteId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastNoteId"] = "";
        }
        if (!("lastDataId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastDataId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Path instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Path}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("histories" in $$parsedSource) {
            $$parsedSource["histories"] = $$createField3_0($$parsedSource["histories"]);
        }
        return new Path(/** @type {Partial<Path>} */($$parsedSource));
    }
}

export class Position {
    /**
     * Creates a new Position instance.
     * @param {Partial<Position>} [$$source = {}] - The source object to create the Position.
     */
    constructor($$source = {}) {
        if (!("top" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["top"] = 0;
        }
        if (!("left" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["left"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("menuWidth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["menuWidth"] = 0;
        }
        if (!("splitter" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["splitter"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Position}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position(/** @type {Partial<Position>} */($$parsedSource));
    }
}

export class Setting {
    /**
     * Creates a new Setting instance.
     * @param {Partial<Setting>} [$$source = {}] - The source object to create the Setting.
     */
    constructor($$source = {}) {
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {Position | null}
             */
            this["position"] = null;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {Path | null}
             */
            this["path"] = null;
        }
        if (!("lookAndFeel" in $$source)) {
            /**
             * @member
             * @type {Look | null}
             */
            this["lookAndFeel"] = null;
        }
        if (!("git" in $$source)) {
            /**
             * @member
             * @type {Git | null}
             */
            this["git"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Setting}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType10;
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField0_0($$parsedSource["position"]);
        }
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField1_0($$parsedSource["path"]);
        }
        if ("lookAndFeel" in $$parsedSource) {
            $$parsedSource["lookAndFeel"] = $$createField2_0($$parsedSource["lookAndFeel"]);
        }
        if ("git" in $$parsedSource) {
            $$parsedSource["git"] = $$createField3_0($$parsedSource["git"]);
        }
        return new Setting(/** @type {Partial<Setting>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Font.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Editor.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = Position.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = Path.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = Look.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = Git.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
